Repository textlint-ja/textlint-rule-preset-ja-spacing, pull requests merged in 2024-04, with the labels that each got.

#64 feat(ja-space-between-half-and-full-width): add `allows` option
  packages/textlint-rule-ja-space-between-half-and-full-width/README.md
  packages/textlint-rule-ja-space-between-half-and-full-width/package.json
  packages/textlint-rule-ja-space-between-half-and-full-width/src/index.js
  packages/textlint-rule-ja-space-between-half-and-full-width/test/index-test.js
  yarn.lock
Labels: Type: Feature

#68 fix(ja-space-between-half-and-full-widt): Collect dependencies
  packages/textlint-rule-ja-space-between-half-and-full-width/package.json
Labels: Type: Bug

#70 fix(ja-nakaguro-or-halfwidth-space-between-katakana): replace match-index with String.prototype.matchAll
  packages/textlint-rule-ja-nakaguro-or-halfwidth-space-between-katakana/package.json
  packages/textlint-rule-ja-nakaguro-or-halfwidth-space-between-katakana/src/index.js
Labels: Type: Refactoring

#74 refactor(ja-no-space-around-parentheses): replace match-index with String.prototype.matchAll
  packages/textlint-rule-ja-no-space-around-parentheses/package.json
  packages/textlint-rule-ja-no-space-around-parentheses/src/index.js
Labels: Type: Refactoring

#73 refactor(ja-space-after-question): replace match-index with String.prototype.matchAll
  packages/textlint-rule-ja-space-after-question/package.json
  packages/textlint-rule-ja-space-after-question/src/index.js
Labels: Type: Refactoring

#72 refactor(ja-space-after-exclamation): replace match-index with String.prototype.matchAll
  packages/textlint-rule-ja-space-after-exclamation/package.json
  packages/textlint-rule-ja-space-after-exclamation/src/index.js
Labels: Type: Refactoring

#76 refactor(ja-space-between-half-and-full-width): replace match-index with String.prototype.matchAll
  packages/textlint-rule-ja-space-between-half-and-full-width/package.json
  packages/textlint-rule-ja-space-between-half-and-full-width/src/index.js
Labels: Type: Refactoring

#75 refactor(ja-no-space-between-full-width): replace match-index with String.prototype.matchAll
  packages/textlint-rule-ja-no-space-between-full-width/package.json
  packages/textlint-rule-ja-no-space-between-full-width/src/index.js
Labels: Type: Refactoring
